import type { Dict } from 'typesdk/types';
import { Box, type SxProps } from '@mui/material';
import React, { HTMLAttributes, forwardRef, memo } from 'react';

import { cn } from '@/utils/react';


const DEFAULT_SX: Dict<SxProps> = {
  boxicons: {
    fontFamily: 'boxicons !important',
    fontWeight: 400,
    fontStyle: 'normal',
    fontFeatureSettings: 'normal',
    fontVariant: 'normal',
    lineHeight: 1,
    textRendering: 'auto',
    display: 'inline-block',
    textTransform: 'none',
    speak: 'none',
    WebkitFontSmoothing: 'antialiased',
  },
  'fonts.google': {
    fontFamily: '"Material Symbols Outlined" !important',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: '24px',
    lineHeight: 1,
    letterSpacing: 'normal',
    textTransform: 'none',
    display: 'inline-block',
    whiteSpace: 'nowrap',
    wordWrap: 'normal',
    direction: 'ltr',
    WebkitFontFeatureSettings: '"liga"',
    WebkitFontSmoothing: 'antialiased',
  },
};

const UNICODE_DICT = {
  'calendar-clock': '"\\f540"',
  'bx-error': '"\\eac5"',
  'bx-bell': '"\\e9d2"',
  'bxs-bell': '"\\ecc9"',
  'bx-home': '"\\eb12"',
  'bx-id-card': '"\\eb1a"',
  'bx-face': '"\\ead0"',
  'bx-archive': '"\\e9b0"',
  'bx-log-out': '"\\eb4f"',
  'bx-chalkboard': '"\\ea3e"',
  'bx-user-circle': '"\\ec65"',
  'bx-ghost': '"\\eaee"',
  'id-card': '"\\ea67"',
  'bx-lock': '"\\eb49"',
  'bx-lock-alt': '"\\eb4a"',
  'bx-loader-alt': '"\\eb46"',
  'iot-device': '"\\e283"',
  'bx-menu': '"\\eb5f"',
  'box-focus': '"\\e9fe"',
  'bx-shape-square': '"\\ec00"',
  'power-plug': '"\\e63c"',
  'bx-cog': '"\\ea6e"',
  'arrow-back': '"\\e5c4"',
  'bx-arrow-back': '"\\e9b4"',
  'bx-chevron-left': '"\\ea4d"',
  'bx-plus': '"\\ebc0"',
  'bx-x': '"\\ec8d"',
  'bx-paint': '"\\eba7"',
  'bx-paint-roll': '"\\eba8"',
  'format-color-fill': '"\\e23a"',
  'menu-side-left': '"\\e9bd"',
  'menu-open': '"\\f3d2"',
  'bx-loader': '"\\eb45"',
  'bx-plus-circle': '"\\ebc1"',
  'bx-chevron-right': '"\\ea50"',
  'bx-chevron-down': '"\\ea4a"',
  'bx-search': '"\\ebf8"',
  'bx-search-alt': '"\\ebf9"',
  'bx-file-blank': '"\\ead6"',
  'bx-chevron-up': '"\\ea57"',
  'bx-youtube': '"\\e992"',
  'bx-link': '"\\eb3c"',
  'bx-link-alt': '"\\eb3d"',
  'bx-key': '"\\eb28"',
  'lock-open': '"\\e898"',
  'bx-play-arrow': '"\\ebbd"',
  'bx-server': '"\\ebfd"',
  'lock-open-right': '"\\f656"',
  'tab-close-right': '"\\f746"',
  'sportive-flag': '"\\f06e"',
  'n-board': '"\\f045"',
  'data-exploration': '"\\e76f"',
  'bx-check': '"\\ea41"',
  'shadow-add': '"\\f584"',
  'manage-search': '"\\f02f"',
  'dataset-linked': '"\\f8ef"',
  'dashboard-plus': '"\\e99b"',
  'unfold-more': '"\\e5d7"',
  'unfold-less': '"\\e5d6"',
  'email-alt': '"\\e0e6"',
  'dark-mode': '"\\e51c"',
  'light-mode': '"\\e518"',
  'ar-stickers': '"\\e983"',
  'attach-file': '"\\f841"',
  'bx-paper-plane': '"\\ebab"',
  'media-folder': '"\\e8a7"',
  'waving-hand': '"\\e766"',
  'note-stack': '"\\f562"',
  'bx-notepad': '"\\eba2"',
  'bx-trash': '"\\ec51"',
  'bx-trash-alt': '"\\ec50"',
  'bx-tv': '"\\ec57"',
  'restore-from-trash': '"\\e938"',
  'currency-notes': '"\\ef63"',
  'finance-mode': '"\\ef92"',
  'credit-card': '"\\e870"',
  host: '"\\f3d9"',
  institutions: '"\\f1d0"',
  contacts: '"\\e0ba"',
  explore: '"\\e87a"',
  security: '"\\e32a"',
  face: '"\\e87c"',
  forum: '"\\e0bf"',
  chat: '"\\e0b7"',
  lock: '"\\e897"',
  topic: '"\\e8de"',
  document: '"\\e873"',
  dashboard: '"\\e871"',
  database: '"\\f20e"',
  analytics: '"\\e4fc"',
  bolt: '"\\ea0b"',
  menu: '"\\e5d2"',
  flow: '"\\e97a"',
  save: '"\\e161"',
  dns: '"\\e875"',
  cases: '"\\e992"',
  label: '"\\e892"',
  hashtag: '"\\eac7"', //# e9ef
  timer: '"\\e425"',
  'help-circle': '"\\e887"',
  calendar: '"\\e935"',
  smile: '"\\e7f2"',
  send: '"\\e163"',
  other: '"\\e47b"',
  task: '"\\e2e6"',
  archive: '"\\e149"',
  mail: '"\\e158"',
  login: '"\\ea77"',
  key: '"\\e73c"',
  signature: '"\\f74c"',
  group: '"\\e7ef"',
  bank: '"\\e84f"',
  briefcase: '"\\e8f9"',
  'numeric-pin': '"\\f045"',
  password: '"\\f042"',
  logout: '"\\e9ba"',
  'security-warn': '"\\f0dc"',
  'shield-locked': '"\\f592"',
  shield: '"\\e9e0"',
  'secure-shield': '"\\e32a"',
  translate: '"\\e8e2"',
  language: '"\\e894"',
  markdown: '"\\f552"',
  doc: '"\\f5a1"',
  fingerprint: '"\\e90d"',
  'content-copy': '"\\e14d"',
  visibility: '"\\e8f4"',
  'visibility-off': '"\\e8f5"',
  'file-save': '"\\f17f"',
  restart: '"\\f053"',
  category: '"\\e574"',
  wallet: '"\\e850"',
  currency: '"\\e227"',
  number: '"\\eb8d"',
  person: '"\\e7fd"',
  extension: '"\\e87b"',
  checklist: '"\\e6b1"',
  approval: '"\\e982"',
  'edit-note': '"\\e745"',
  'calendar-month': '"\\ebcc"',
  'file-upload': '"\\e9fc"',
  'alphabet-sort': '"\\e053"',
  'check-outline': '"\\e92f"',
  'calendar-event': '"\\e878"',
  'chevron-left': '"\\e5cb"',
  'chevron-right': '"\\e5cc"',
  'chevron-down': '"\\e5cf"',
  'chevron-up': '"\\e5ce"',
  'celular-signal': '"\\e202"',
  'add-box': '"\\e146"',
  'location-searching': '"\\e1b7"',
  'cloud-upload': '"\\e2c3"',
  'inventory-check': '"\\e179"',
  location: '"\\e0c8"',
  article: '"\\ef42"',
  phone: '"\\e325"',
  car: '"\\e531"',
  lan: '"\\eb2f"',
  devices: '"\\e1b1"',
  filter: '"\\ef4f"',
  settings: '"\\e8b8"',
  qrcode: '"\\f206"',
  verified: '"\\ef76"',
  bell: '"\\e7f4"',
  close: '"\\e5cd"',
  csv: '"\\e6cf"',
  function: '"\\f866"',
  headphones: '"\\f01f"',
  videocam: '"\\e04b"',
  workspaces: '"\\e1a0"',
  stack: '"\\f500"',
  api: '"\\f1b7"',
  info: '"\\e88e"',
  warning: '"\\e002"',
  http: '"\\e902"',
  refresh: '"\\e5d5"',
  publish: '"\\e255"',
  movie: '"\\e02c"',
  mi: '"\\ebed"',
  assignment: '"\\e85d"',
  'shield-error': '"\\f012"',
  'bell-rounded': '"\\e994"',
  'file-open': '"\\eaf3"',
  'folder-open': '"\\e2c8"',
  'top-panel-close': '"\\f733"',
  'top-panel-open': '"\\f732"',
  'box-edit': '"\\f5a6"',
  'more-vertical': '"\\e5d4"',
  'add-picture': '"\\e439"',
  'unread-mailbox': '"\\e89b"',
  'dev-board': '"\\e30d"',
  'space-dashboard': '"\\e66b"',
  'group-off': '"\\e747"',
  'group-add': '"\\e7f0"',
  'box-add': '"\\f5a5"',
  'text-fields': '"\\e262"',
  'paint-brush': '"\\e243"',
  'color-palette': '"\\e40a"',
  'add-circle': '"\\e147"',
  'play-circle': '"\\e1c4"',
  'pause-circle': '"\\e1a2"',
  'bx-pause': '"\\ebae"',
  school: '"\\e80c"',
  work: '"\\e8f9"',
  science: '"\\ea4b"',
  pending: '"\\ef64"',
  add: '"\\e145"',
  delete: '"\\e872"',
  report: '"\\e160"',
  mystery: '"\\f5e1"',
  star: '"\\e838"',
  heart: '"\\e87d"',
  unknown: '"\\eabd"',
  bug: '"\\e868"',
  exclamation: '"\\f22f"',
  folder: '"\\e2c7"',
  download: '"\\f090"',
  pdf: '"\\e415"',
  autorenew: '"\\e863"',
  check: '"\\e5ca"',
  theaters: '"\\e8da"',
  'archive-box': '"\\e1a1"',
  'arrow-forward': '"\\e5c8"',
  'delete-alt': '"\\e92b"',
  'shield-warning': '"\\f0dc"',
  'folder-plus': '"\\e2cc"',
  'account-group': '"\\e7ef"',
  'account-box': '"\\e851"',
  'data-object': '"\\ead3"',
  'playlist-add': '"\\e03b"',
  'playlist-remove': '"\\eb80"',
  'replay-10': '"\\e059"',
  'forward-10': '"\\e056"',
  'volume-up': '"\\e050"',
  'volume-off': '"\\e04f"',
  'skip-next': '"\\e044"',
  speed: '"\\e9e4"',
  pause: '"\\e034"',
  fullscreen: '"\\e5d0"',
  'fullscreen-exit': '"\\e5d1"',
  edit: '"\\e3c9"',
  flag: '"\\e153"',
  'toggle-on': '"\\e9f6"',
  'toggle-off': '"\\e9f5"',
  'do-not-disturbe': '"\\e644"',
  'clear-list': '"\\e0b8"',
  'step-right': '"\\f6fe"',
  'waterfall-chart': '"\\ea00"',
  'account-circle': '"\\e853"',
  'up-down-thumbs': '"\\e8dd"',
  'drag-indicator': '"\\e945"',
  'add-library': '"\\e02e"',
  'contract-delete': '"\\f5a2"',
  'readiness-score': '"\\f6dd"',
  'double-chevron-left': '"\\eac3"',
  'double-chevron-right': '"\\eac9"',
  'verify-warning': '"\\f654"',
  'institution-add': '"\\eb62"',
  'person-add': '"\\e7fe"',
  'build-tools': '"\\ea3c"',
  home: '"\\e88a"',
  add2: '"\\f3dd"',
  road: '"\\f472"',
  license: '"\\eb04"',
  ballot: '"\\e172"',
  hub: '"\\e9f4"',
  experiment: '"\\e686"',
  institution: '"\\e7ee"',
  history: '"\\e889"',
  'wifi-off': '"\\e648"',
};

const UNICODE_ICON_ALIAS = {};



export interface IconProps extends HTMLAttributes<HTMLElement> {
  provider?: 'boxicons' | 'fonts.google';
  icon?: keyof typeof UNICODE_DICT | keyof typeof UNICODE_ICON_ALIAS;
}


/* eslint-disable-next-line react/display-name */
const Icon = forwardRef<HTMLElement, IconProps>(({ provider, icon, className, color, ...props }: IconProps, ref) => {
  const i: string = (icon ?
    Object.keys(UNICODE_ICON_ALIAS).includes(icon as string)
      ? (UNICODE_ICON_ALIAS as Dict<string>)[icon]
      : icon
    : 'bx-error') as unknown as string;

  const p = provider && ['boxicons', 'fonts.google'].includes(provider) ?
    provider :
    (
      i.startsWith('bx-') ||
      i.startsWith('bxs-')
    ) ?
      'boxicons' :
      'fonts.google';

  return (
    <Box
      { ...props }
      component="i"
      role={props.role ?? 'icon'}
      ref={ref}
      className={cn('icon', 'drawer-ui-icon-element', className)}
      sx={Object.assign({}, {
        '&::before': {
          content: UNICODE_DICT[i as unknown as keyof typeof UNICODE_DICT],
        },

        color,
      }, DEFAULT_SX[p])}
    />
  );
});

export default memo(Icon);
